Repository Sifon98/GitVersion, pull requests merged in 2020-09, with the labels that each got.

#2 feature 1
  collaboration.html
Labels: bug

#3 feature 2
  collaboration.html
Labels: Waiting for review

#1 this works
  collaboration.html
Labels: Waiting for review, documentation
